import type { FullProfile } from "@/lib/queries";

/**
 * Hardcoded profile used by /t/demo so the public profile renderer can be
 * previewed without a database connection. Shape mirrors getFullProfile().
 */
export const DEMO_PROFILE: FullProfile = {
  user: {
    id: 0,
    clerkId: "demo",
    email: "dave@example.com",
    name: "Dave Wilson Plumbing",
    trade: "Plumber",
    phone: "07700 900123",
    location: "Manchester",
    areasCovered:
      "Manchester city centre, Salford, Stockport, Trafford, Bury, Bolton. Happy to travel for bigger jobs.",
    about:
      "Twelve years on the tools. Boilers, leaks, full bathrooms — emergency or planned. Reliable, on time, fair prices. Fully insured, Gas Safe registered.",
    yearsExperience: 12,
    responseTime: "Usually within an hour",
    paymentMethods: "Cash, bank transfer, card on completion",
    availabilityStatus: "taking_on_work",
    accountGoal: "business",
    publicEmail: null,
    googleReviewUrl: "https://www.google.com/maps",
    googleRating: 4.9,
    googleReviewCount: 84,
    facebookUrl: "https://facebook.com",
    instagramUrl: "https://instagram.com/dave_the_plumber",
    tiktokUrl: "https://tiktok.com/@daveplumber",
    websiteUrl: "davewilsonplumbing.com.au",
    whatsappNumber: "07700 900123",
    introVideoUrl: null,
    emergencyNumber: "07700 900124",
    profilePhotoUrl:
      "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=400&q=80",
    bannerImageUrl:
      "https://images.unsplash.com/photo-1581094794329-c8112a89af12?w=1600&q=80",
    accentColor: "#F97316",
    plan: "paid",
    slug: "demo",
    stripeCustomerId: null,
    stripeSubscriptionId: null,
    onboardingComplete: true,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  services: [
    {
      id: 1,
      userId: 0,
      serviceName: "Boiler installs & servicing",
      description:
        "Gas, electric and combi boilers. Full service or warranty work. Worcester-Bosch accredited.",
      displayOrder: 0,
      createdAt: new Date(),
    },
    {
      id: 2,
      userId: 0,
      serviceName: "Bathroom fit-outs",
      description:
        "Full bathroom design and install — tiles, plumbing, electrics co-ordinated. Typical job 4-7 days.",
      displayOrder: 1,
      createdAt: new Date(),
    },
    {
      id: 3,
      userId: 0,
      serviceName: "Leak & burst-pipe repair",
      description: "Same-day callouts when I can. Trace, repair, dry out, restore.",
      displayOrder: 2,
      createdAt: new Date(),
    },
    {
      id: 4,
      userId: 0,
      serviceName: "Tap, toilet & shower replacement",
      description: null,
      displayOrder: 3,
      createdAt: new Date(),
    },
  ],
  photos: [
    {
      id: 1,
      userId: 0,
      photoUrl:
        "https://images.unsplash.com/photo-1564540586988-aa4e53c3d799?w=800&q=80",
      caption: "Recent bathroom refit, Didsbury",
      type: "gallery",
      pairId: null,
      displayOrder: 0,
      createdAt: new Date(),
    },
    {
      id: 2,
      userId: 0,
      photoUrl:
        "https://images.unsplash.com/photo-1552321554-5fefe8c9ef14?w=800&q=80",
      caption: "Combi boiler swap, Chorlton",
      type: "gallery",
      pairId: null,
      displayOrder: 1,
      createdAt: new Date(),
    },
    {
      id: 3,
      userId: 0,
      photoUrl:
        "https://images.unsplash.com/photo-1620626011761-996317b8d101?w=800&q=80",
      caption: "Copper repipe under floor",
      type: "gallery",
      pairId: null,
      displayOrder: 2,
      createdAt: new Date(),
    },
    {
      id: 4,
      userId: 0,
      photoUrl:
        "https://images.unsplash.com/photo-1556909114-f6e7ad7d3136?w=800&q=80",
      caption: "Kitchen tap install, Salford",
      type: "gallery",
      pairId: null,
      displayOrder: 3,
      createdAt: new Date(),
    },
    {
      id: 10,
      userId: 0,
      photoUrl:
        "https://images.unsplash.com/photo-1581858726788-75bc0f6a952d?w=800&q=80",
      caption: "Before",
      type: "before",
      pairId: null,
      displayOrder: 0,
      createdAt: new Date(),
    },
    {
      id: 11,
      userId: 0,
      photoUrl:
        "https://images.unsplash.com/photo-1564540583246-934409427776?w=800&q=80",
      caption: "After",
      type: "after",
      pairId: 10,
      displayOrder: 0,
      createdAt: new Date(),
    },
  ],
  certifications: [
    {
      id: 1,
      userId: 0,
      name: "Gas Safe registered",
      badgeUrl: null,
      displayOrder: 0,
      createdAt: new Date(),
    },
    {
      id: 2,
      userId: 0,
      name: "CIPHE member",
      badgeUrl: null,
      displayOrder: 1,
      createdAt: new Date(),
    },
    {
      id: 3,
      userId: 0,
      name: "WaterSafe approved",
      badgeUrl: null,
      displayOrder: 2,
      createdAt: new Date(),
    },
    {
      id: 4,
      userId: 0,
      name: "Public liability £5m",
      badgeUrl: null,
      displayOrder: 3,
      createdAt: new Date(),
    },
  ],
  testimonials: [
    {
      id: 1,
      userId: 0,
      customerName: "Sarah M.",
      quote:
        "Boiler packed in on a Sunday — Dave was round within the hour and had us back up by tea time. Fair price, no faff.",
      location: "Didsbury",
      displayOrder: 0,
      createdAt: new Date(),
    },
    {
      id: 2,
      userId: 0,
      customerName: "James & Priya",
      quote:
        "Full bathroom refit. Turned up when he said, cleaned up every day, the finish is brilliant. Already booked him for the en-suite.",
      location: "Chorlton",
      displayOrder: 1,
      createdAt: new Date(),
    },
    {
      id: 3,
      userId: 0,
      customerName: "Mike H.",
      quote:
        "Honest bloke. Quoted exactly what he charged. Will be using again.",
      location: null,
      displayOrder: 2,
      createdAt: new Date(),
    },
  ],
  sections: [
    { id: 1, userId: 0, sectionKey: "banner_image", isEnabled: true, displayOrder: 0 },
    { id: 2, userId: 0, sectionKey: "profile_photo", isEnabled: true, displayOrder: 1 },
    { id: 3, userId: 0, sectionKey: "availability_status", isEnabled: true, displayOrder: 2 },
    { id: 4, userId: 0, sectionKey: "call_button", isEnabled: true, displayOrder: 3 },
    { id: 5, userId: 0, sectionKey: "whatsapp_button", isEnabled: true, displayOrder: 4 },
    { id: 6, userId: 0, sectionKey: "emergency_callout", isEnabled: true, displayOrder: 5 },
    { id: 7, userId: 0, sectionKey: "about_me", isEnabled: true, displayOrder: 6 },
    { id: 8, userId: 0, sectionKey: "certifications", isEnabled: true, displayOrder: 7 },
    { id: 9, userId: 0, sectionKey: "testimonials", isEnabled: true, displayOrder: 8 },
    { id: 10, userId: 0, sectionKey: "services_list", isEnabled: true, displayOrder: 9 },
    { id: 11, userId: 0, sectionKey: "photo_gallery", isEnabled: true, displayOrder: 10 },
    { id: 12, userId: 0, sectionKey: "before_after_photos", isEnabled: true, displayOrder: 11 },
    { id: 13, userId: 0, sectionKey: "google_reviews", isEnabled: true, displayOrder: 12 },
    { id: 14, userId: 0, sectionKey: "quote_form", isEnabled: true, displayOrder: 13 },
    { id: 15, userId: 0, sectionKey: "areas_covered", isEnabled: true, displayOrder: 14 },
    { id: 16, userId: 0, sectionKey: "payment_methods", isEnabled: true, displayOrder: 15 },
    { id: 17, userId: 0, sectionKey: "facebook_link", isEnabled: true, displayOrder: 16 },
    { id: 18, userId: 0, sectionKey: "instagram_link", isEnabled: true, displayOrder: 17 },
    { id: 19, userId: 0, sectionKey: "tiktok_link", isEnabled: true, displayOrder: 18 },
    { id: 20, userId: 0, sectionKey: "website_link", isEnabled: true, displayOrder: 19 },
    { id: 21, userId: 0, sectionKey: "custom_links", isEnabled: true, displayOrder: 20 },
  ],
  customLinks: [
    {
      id: 1,
      userId: 0,
      title: "Watch my boiler tips on YouTube",
      url: "https://youtube.com/@daveplumber",
      displayOrder: 0,
      createdAt: new Date(),
    },
    {
      id: 2,
      userId: 0,
      title: "Book a slot online",
      url: "https://calendly.com/daveplumber",
      displayOrder: 1,
      createdAt: new Date(),
    },
  ],
  education: [],
};
